version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gocyclo
    - dupl
    - misspell
    - unconvert
    - goconst
    - gocritic
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gocyclo